---
# tasks file for installJenkins
- name: Update hosts file and apply updates
  command: 'echo  "192.168.1.190   jenkins.linuxtechi.com" | sudo tee -a /etc/hosts'
  
  
- name: Install all the available updates
  dnf:
    name: "*"
    state: latest

# - name: Unconditionally reboot the machine with all defaults
#   reboot:


- name: Download file and force basic auth
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    force_basic_auth: yes

- name: Import GPG key for Jenkins packages
  ansible.builtin.rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install java
  dnf:
    name: java-11-openjdk-devel
    state: latest

    
- name: Install jenkins
  dnf:
    name: jenkins
    state: latest

- name: start and enable jenkins
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes

- name: enabled permit traffic in default zone on port 8080/tcp
  ansible.posix.firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled

- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded
